// Os recursos de script mudaram para a v2.3.0; veja
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para obter mais informações
itens_pegos = ds_list_create()

posicoes = {
	"obj_chumbo": {"x": 388, "y": 664},
	"obj_mapa": {"x": 386, "y": 244},
	"obj_traje_davi": {"x": 1230, "y": 441},
	"obj_traje_roger": {"x": 1162, "y": 441},
	"obj_municao": {"x": 274, "y": 210},
	"obj_radio": {"x": 500, "y": 482},
	"obj_pilha": {"x": 250, "y": 213},
	"obj_machado": {"x": 1160, "y": 242},
	"obj_metralhadora": {"x": 1039, "y": 279},
	"obj_picareta": {"x": 1199, "y": 277},
	"obj_pistola": {"x": 1237, "y": 279},
	"obj_analgesico": {"x": 1240, "y": 167},
	"obj_ansiolitico": {"x": 1210, "y": 158},
	"obj_antibiotico": {"x": 1152, "y": 160},
	"obj_aspirina": {"x": 1181, "y": 159},
	"obj_curativo": {"x": 1105, "y": 168},
	"obj_baralho": {"x": 335, "y": 170},
	"obj_contador_geiger": {"x": 922.5, "y": 648},
	"obj_domino": {"x": 854, "y": 642},
	"obj_saco_lixo": {"x": 811, "y": 657},
	"obj_tv": {"x": 864, "y": 544},
	"obj_inseticida": {"x":273, "y":293},
	"obj_ferramentas": {"x":247, "y":339},
	"obj_agua_sanitaria": {"x":330,"y":255},
	"obj_espanador": {"x":350, "y":247},
	"obj_meredith": {"x":775, "y":530},
	"obj_davi": {"x":1121, "y":354},
}

casa = [
	["obj_mapa", 1370, 534],
	["obj_traje_davi", 245, 140],
	["obj_traje_roger", 312, 140],
    ["obj_radio", 548, 677],
    ["obj_machado", 1494, 785],
    ["obj_metralhadora", 308.5, 720],
    ["obj_picareta", 464, 975.6163],
    ["obj_pistola", 613, 703.5],
    ["obj_baralho", 936, 692],
    ["obj_contador_geiger", 929, 855],
    ["obj_domino", 945, 804],
    ["obj_tv", 1265, 944],
	["obj_ferramentas", 378, 216],
	["obj_espanador", 468, 454],
	["obj_meredith", 1542, 438],
	["obj_davi",281,221]
]

qtde_slots = {
	"obj_chumbo": 1,
	"obj_mapa": 1,
	"obj_traje_davi": 2,
	"obj_traje_roger": 2,
	"obj_davi": 5,
	"obj_meredith": 1,
	"obj_arroz_frango": 1, 
	"obj_bolo_chocolate": 1,
	"obj_bolo_quatro_quartos": 1, 
	"obj_chucrute": 1,
	"obj_escondidinho": 1,
	"obj_ovo_mexido": 1,
	"obj_salada": 1,
	"obj_cookie": 1,
	"obj_municao": 1,
	"obj_radio": 1,
	"obj_pilha": 1,
	"obj_machado": 1,
	"obj_metralhadora": 2,
	"obj_picareta": 1,
	"obj_pistola": 1,
	"obj_analgesico": 1,
	"obj_ansiolitico": 1,
	"obj_antibiotico": 1,
	"obj_aspirina": 1,
	"obj_curativo": 1,
	"obj_baralho": 1,
	"obj_contador_geiger": 2,
	"obj_domino": 1,
	"obj_saco_lixo": 1,
	"obj_tv": 3,
	"obj_acucar": 1,
	"obj_agua": 1,
	"obj_alface": 1,
	"obj_arroz": 1,
	"obj_batata": 1,
	"obj_cerveja": 1,
	"obj_chocolate": 1,
	"obj_farinha": 1,
	"obj_frango": 1,
	"obj_ovo": 1,
	"obj_repolho": 1,
	"obj_inseticida": 1,
	"obj_ferramentas": 4,
	"obj_agua_sanitaria": 1,
	"obj_argamassa": 1,
	"obj_martelo": 1,
	"obj_chave_fenda": 1,
	"obj_fita_isolante": 1,
	"obj_espanador": 1
}

alimentos = [obj_arroz_frango, obj_cookie, obj_bolo_quatro_quartos, obj_bolo_chocolate, obj_chucrute, obj_escondidinho, obj_salada, obj_ovo_mexido,
			obj_acucar, obj_agua, obj_alface, obj_arroz, obj_batata, obj_cerveja, obj_chocolate, obj_farinha, obj_frango, obj_ovo, obj_repolho]
			
ferramentas = [obj_chave_fenda, obj_argamassa, obj_martelo, obj_fita_isolante]

nomes = {
	"obj_chumbo": "Chumbo",
	"obj_mapa": "Mapa",
	"obj_traje_roger": "Traje Anti-Radiação",
	"obj_traje_davi": "Traje Anti-Radiação",
	"obj_acucar": "Açúcar",
	"obj_agua": "Água",
	"obj_alface": "Alface",
	"obj_arroz": "Arroz",
	"obj_arroz_frango": "Arroz com frango",
	"obj_batata": "Batata",
	"obj_bolo_chocolate": "Bolo de Chocolate",
	"obj_bolo_quatro_quartos": "Bolo Quatro Quartos",
	"obj_chucrute": "Chucrute",
	"obj_escondidinho": "Escondidinho",
	"obj_ovo_mexido": "Ovo Mexido",
	"obj_salada": "Salada Caesar",
	"obj_cookie": "Cookie",
	"obj_municao": "Munição",
	"obj_radio": "Rádio",
	"obj_pilha": "Pilha",
	"obj_machado": "Machado",
	"obj_metralhadora": "Metralhadora",
	"obj_picareta": "Picareta",
	"obj_pistola": "Pistola",
	"obj_analgesico": "Analgésico",
	"obj_ansiolitico": "Ansiolítico",
	"obj_antibiotico": "Antibiótico",
	"obj_aspirina": "Aspirina",
	"obj_curativo": "Curativo",
	"obj_baralho": "Baralho",
	"obj_contador_geiger": "Contador Geiger",
	"obj_domino": "Dominó",
	"obj_saco_lixo": "Saco de Lixo",
	"obj_tv": "TV",
	"obj_cerveja": "Cerveja",
	"obj_chocolate": "Chocolate",
	"obj_farinha": "Farinha",
	"obj_frango": "Frango",
	"obj_ovo": "Ovo",
	"obj_repolho": "Repolho",
	"obj_inseticida": "Inseticida",
	"obj_ferramentas": "Ferramentas",
	"obj_agua_sanitaria": "Água Sanitária",
	"obj_argamassa": "Argamassa",
	"obj_martelo": "Martelo",
	"obj_chave_fenda": "Chave de Fenda",
	"obj_fita_isolante": "Fita Isolante",
	"obj_espanador": "Espanador",
	"obj_meredith": "Meredith",
	"obj_davi": "Davi"
}

descricoes = {
	"obj_chumbo": "Usado para concertar vazamentos de radiação.",
	"obj_mapa": "Usado para explorar mundo afora nos eventos de coleta de itens.",
	"obj_traje_roger": "Usado para proteger-se quando for sair do Bunker.",
	"obj_traje_davi": "Usado para proteger-se quando for sair do Bunker.",
	"obj_acucar": "Usado em bolos e outros docinhos.",
	"obj_agua": "Hidrate-se!",
	"obj_alface": "Folhas verdes e saudáveis.",
	"obj_arroz": "Grão asiático suculento e nutritivo.",
	"obj_arroz_frango": "Refeição calórica para um bom almoço pós-apocalíptico.",
	"obj_batata": "Repleta de amido, é disso que você precisa para ter energia!",
	"obj_bolo_chocolate": "Um bolo molhadinho e chocolatudo.",
	"obj_bolo_quatro_quartos": "Bolo de 4 ingredintes: manteiga, açúcar, ovo e farinha, portanto, 4 qautros.",
	"obj_chucrute": "Refeição rica em vitamina C; cura de escorbuto.",
	"obj_escondidinho": "Batata em volta encobrindo uma delícia de frango.",
	"obj_ovo_mexido": "Um jeito único de fazer ovos.",
	"obj_salada": "Uma saladinha leve com crotouns de pão de forma e frango em cubinhos.",
	"obj_cookie": "Quem não gosta de um bom cookie, não é mesmo?",
	"obj_municao": "Utilizada em batalhas para abastacer armas de fogo.",
	"obj_radio": "Utilizado para asssistir programas informativos no bunker.",
	"obj_pilha": "Sem ela, seu rádio para de funcionar em algum tempo, e você fica desatualizado.",
	"obj_machado": "Dá certa quantidade de dano em batalhas.",
	"obj_metralhadora": "Dá muito dano, mas somente se você tiver muniçõa; caso contrário, perderá sua utilizade rápido.",
	"obj_picareta": "Dá menos dano que um machado.",
	"obj_pistola": "Dá menos dano que uma metralhadora.",
	"obj_analgesico": "Usado para diminuir dores e melhorar sua saúde um pouco.",
	"obj_ansiolitico": "Serve para amainar crises de ansiedade.",
	"obj_antibiotico": "Livra de infecções bacterianas.",
	"obj_aspirina": "Cura dores leves na capeça.",
	"obj_curativo": "cura hemorragias e cortes.",
	"obj_baralho": "Bom para jogar em duplas.",
	"obj_contador_geiger": "Use ele com frequência para descobrir se há vazamentos de radiação; não ter um por perto pode ser fatal!",
	"obj_domino": "Bom para jogar em duplas.",
	"obj_saco_lixo": "Recolhe sujeira.",
	"obj_tv": "Não funciona sem sinal de TV!",
	"obj_cerveja": "Álcool em sua forma mais clássica!",
	"obj_chocolate": "Açúcar em sua forma mais clássica!",
	"obj_farinha": "Bom para fazer bolos e massas.",
	"obj_frango": "Protéina em sua forma mais clássica!",
	"obj_ovo": "O cinto de utilizadades da culinária!",
	"obj_repolho": "Usado para fazer chucrute.",
	"obj_inseticida": "Para matar baratas e outros insetos medonhos.",
	"obj_ferramentas": "Conserta várias coisas no bunker. Não vá esquecer dela!",
	"obj_agua_sanitaria": "Limpa profundamente manchas de mofo nas paredes e sujeiras específicas.",
	"obj_argamassa": "Conserta rachaduras no piso.",
	"obj_martelo": "Destrói as paredes para acessar seu interior.",
	"obj_chave_fenda": "Para acessar as ventilações.",
	"obj_fita_isolante": "Conserta quase tudo!",
	"obj_espanador": "Para limpar locais empoeirados.",
	"obj_meredith": "Meredith pode ser sua maior companheira nessa tragetória. Cuide bem dela.",
	"obj_davi": "Seu filho! Podes interagir com ele e ele te ajudará em muitas tarefas."
}

fome = {
	"obj_arroz_frango": 32, 
	"obj_bolo_chocolate": 25,
	"obj_bolo_quatro_quartos": 25, 
	"obj_chucrute": 12,
	"obj_escondidinho": 28,
	"obj_ovo_mexido": 14,
	"obj_salada": 17,
	"obj_cookie": 15,
	"obj_alface": 2,
	"obj_batata": 7,
	"obj_chocolate": 6,
	"obj_frango": 10,
	"obj_ovo": 3,
	"obj_repolho": 2,
}

alimentos_consumiveis =  [obj_arroz_frango, obj_cookie, obj_bolo_quatro_quartos, obj_bolo_chocolate, 
						obj_chucrute, obj_escondidinho, obj_salada, obj_ovo_mexido,
						obj_alface, obj_batata, obj_chocolate, obj_frango, obj_ovo, obj_repolho]
						
remedios = [obj_analgesico, obj_curativo, obj_ansiolitico, obj_aspirina, obj_antibiotico]

pulou_dia = false

armas = [obj_machado, obj_picareta, obj_pistola, obj_metralhadora]